# Configuration Module
from .config import (
    CSV_PATH, BASE_IMAGE_PATH, IMAGE_SIZE, BATCH_SIZE,
    LEARNING_RATE, EPOCHS, DEVICE, RANDOM_SEED,
    clear_gpu_memory, CHECKPOINT_DIR, LOGS_DIR,
    NUM_WORKERS, PIN_MEMORY, PERSISTENT_WORKERS, USE_AMP,
    WEIGHT_DECAY, DROPOUT_RATE, LOSS_TYPE,
    FREEZE_IMAGE_ENCODER_EPOCHS, GRADIENT_CLIP_NORM,
    USE_LOG_TRANSFORM, IMAGE_MODEL, IMAGE_OUTPUT_DIM,
    METADATA_OUTPUT_DIM, FUSION_HIDDEN_DIMS, USE_RESIDUAL,
    CATEGORY_EMBEDDING_DIM, USE_ATTENTION_FUSION, 
    ATTENTION_EMBED_DIM, ATTENTION_NUM_HEADS
)

# Stage 2: Explanation Configuration
from .explanation_config import (
    LLM_MODEL_NAME, LLM_DEVICE, LLM_LOAD_IN_8BIT, LLM_LOAD_IN_4BIT,
    LLM_MAX_NEW_TOKENS, LLM_TEMPERATURE,
    SHAP_BACKGROUND_SAMPLES, SHAP_ALGORITHM,
    ENABLE_MODALITY_CONTRIBUTION, ENABLE_FEATURE_IMPORTANCE,
    EXPLANATION_OUTPUT_DIR, SAVE_EXPLANATIONS_TO_FILE,
    get_llm_config, get_shap_config, print_explanation_config
)

__all__ = [
    # Paths
    'CSV_PATH', 'BASE_IMAGE_PATH', 'CHECKPOINT_DIR', 'LOGS_DIR',
    # Device & Performance
    'DEVICE', 'USE_AMP', 'NUM_WORKERS', 'PIN_MEMORY', 'PERSISTENT_WORKERS',
    # Model Architecture
    'IMAGE_SIZE', 'IMAGE_MODEL', 'IMAGE_OUTPUT_DIM', 'METADATA_OUTPUT_DIM',
    'FUSION_HIDDEN_DIMS', 'DROPOUT_RATE', 'USE_RESIDUAL', 'CATEGORY_EMBEDDING_DIM',
    # Attention Fusion
    'USE_ATTENTION_FUSION', 'ATTENTION_EMBED_DIM', 'ATTENTION_NUM_HEADS',
    # Training
    'BATCH_SIZE', 'EPOCHS', 'LEARNING_RATE', 'WEIGHT_DECAY', 'LOSS_TYPE',
    'FREEZE_IMAGE_ENCODER_EPOCHS', 'GRADIENT_CLIP_NORM', 'USE_LOG_TRANSFORM',
    # Utilities
    'RANDOM_SEED', 'clear_gpu_memory',
    # Stage 2: Explanation
    'LLM_MODEL_NAME', 'LLM_DEVICE', 'LLM_LOAD_IN_8BIT', 'LLM_LOAD_IN_4BIT',
    'LLM_MAX_NEW_TOKENS', 'LLM_TEMPERATURE',
    'SHAP_BACKGROUND_SAMPLES', 'SHAP_ALGORITHM',
    'ENABLE_MODALITY_CONTRIBUTION', 'ENABLE_FEATURE_IMPORTANCE',
    'EXPLANATION_OUTPUT_DIR', 'SAVE_EXPLANATIONS_TO_FILE',
    'get_llm_config', 'get_shap_config', 'print_explanation_config'
]
